---
name: tests

on:
  push:
  pull_request:
  schedule:
    - cron: "0 0 * * *"

jobs:
  tests:
    runs-on: ubuntu-20.04

    strategy:
      fail-fast: true
      matrix:
        php: [7.4, 8.0]

    name: PHP ${{ matrix.php }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup PHP environment
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip
          tools: composer:v2
          coverage: none

      - name: Install dependencies
        run: composer install

      - name: Build container images
        run: ./stack build

      - name: Run unit/feature tests
        run: ./stack test

      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
        if: github.event.release

      - name: Publish container images
        run: |
          docker push ghcr.io/sitepilot/lshttpd
          docker push ghcr.io/sitepilot/runtime:7.4
          docker push ghcr.io/sitepilot/runtime:8.0
        if: github.event.release

      - name: Debug
        if: ${{ failure() }}
        run: |
          cat .env
          cat stack.yml
